# Generated by Django 3.2.4 on 2021-07-05 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='token',
            field=models.CharField(default='6afafff25448b224d77d1e865be6b5c7', max_length=32),
        ),
    ]
