# Generated by Django 3.2.4 on 2021-07-31 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='active',
            field=models.CharField(default='yes', max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default='example@example.com', max_length=254),
            preserve_default=False,
        ),
    ]
