# Generated by Django 3.2.4 on 2021-07-31 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210731_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tmp_token',
            field=models.CharField(default='12345678912345', max_length=32),
            preserve_default=False,
        ),
    ]
